### ISSUE TITLE
copyright in footer

### ISSUE THREAD

**Issue by Galixte** [MrGabatt/SimplicityForPhpBB32#1]
Hi @MrGabatt ,

i have compared with Winmerge the files between 14 august version and the last (17 august version), you have reverted the changes about your copyright in footer:

```<br />Style {L_POST_BY_AUTHOR} <a href="http://www.artodia.com/">Arty</a> - {L_UPDATE} phpBB 3.2 {L_POST_BY_AUTHOR} MrGaby```Maybe you worked on a old backup from your files.

I didn’t check the alternative color versions from this style.

And i didn’t check your others adaptated styled from Arty.

Sorry for bad news. ;)

See you!

**Comment by MrGabatt** [comment]
Hi,
Thanks for your issue. It's corrected (in all adapted styles).
Alternative color versions inherit the default style, so a single template folder :)
